kind: ConfigMap
apiVersion: v1
metadata:
  name: file-secrets-data
data:
  vault_secrets_info.yaml: |
    ---
    FILE_SECRETS:

       -   VAULT_SECRET_PATH: v1/secret/data/suman-test
           TO_FILE_NAME: /vault-secrets/appsecrets.json
           FILE_FORMAT: json

